name: Dimension_conflict
version: @version@
main: com.github.chaosindustry.dimension_conflict.Dimension_conflict
api-version: 1.15
commands:
  IwannabeaDiamondman:
    description: This is a diamond command.
    usage: /IwannabeaDiamondman [player]
    permission: dimension_conflict.IwannabeaDiamondman
    permission-message: You cannot be diamond, idiot!

commands:
  firegarden:
    description: This is a hyer command.
    usage: /firegarden count [player]
    permission: dimension_conflict.firegarden
    permission-message: Take a dood care of our environment!